### ISSUE TITLE
Support for Firefox

### ISSUE THREAD

**Issue by filips123** [nkjammula/LikeTabs#1]
Please add support for Firefox. It uses almost same format for extensions as Chrome, so you probably just need to publish it to Firefox Add-ons store.

**Comment by nkjammula** [comment]
> Please add support for Firefox. It uses almost same format for extensions as Chrome, so you probably just need to publish it to Firefox Add-ons store.

Thank you, I will be adding support to the firefox as well soon.

**Comment by nkjammula** [comment]
@filips123  I have submitted Firefox version of Like Tabs for review. once it is approved, I will send out the published version of it. once again, thank you for showing interest in Like Tabs.

**Comment by nkjammula** [comment]
@filips123  Please find the like tabs addon ported for Mozilla. 
https://addons.mozilla.org/en-US/firefox/addon/like-tabs/
